name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4 h
         with:
          distribution: temurin
          java-version: 25

      - name: Build Project
        run: mvn clean package -DskipTests

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 152.42.254.59 >> ~/.ssh/known_hosts

      - name: Run Playbook
        run: |
          ansible-playbook -i inventory.ini task3.yml

  notify-failure:
    if: failure()

    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: GitHub Actions Build Failed

          to: horngly49@gmail.com

          from: GitHub Actions

          body: |
            Build failed.

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref_name }}

            Commit:
            ${{ github.event.head_commit.message }}

            Author:
            ${{ github.actor }}
